markdown: rdiscount
permalink: /:year/:month/:day/:title.html #博文的固定链接
paginate: 20				  #分页时每页博文数量
author: Devchen				  #自定义常量
  name: Devchen.com
  email: joinfun@foxmail.com
  url: http://devchen.com
  qq: 1129426062
duoshuo: Devchen
beian: taplate
cnzz: 1000386786
weibo: taplate
github: Joinfun
pygments: true
safe: true
about: "这里是 Devchen 的个人博客，创建于 2014 年。使用基于 Jekyllekyll @ GitHub 的 Yonsm 模板。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
