markdown: rdiscount
permalink: /:title/  			#博文的固定链接
url: http://devchen.com
name: Devchen.com
author: Devchen	
qq: 1129426062
email: joinfun@foxmail.com
duoshuo: Devchen
beian: taplate
cnzz: 1000386786
weibo: taplate
github: Joinfun
pygments: true
safe: true
paginate: 20				#分页时每页博文数量
about: "这里是 Devchen 的个人博客，创建于 2014 年。使用基于 Jekyllekyll @ GitHub 的 Yonsm 模板。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
