markdown: rdiscount
permalink: /:title/  			#博文的固定链接
url: https://joinfun.github.com
name: Devchen.com
author: Devchen	
qq: 1129426062
email: joinfun@foxmail.com
duoshuo: Devchen
beian: taplate
cnzz: 1000386786
weibo: taplate
github: Joinfun
pygments: true
safe: true
auto: true
paginate: 10				#分页时每页博文数量
about: "这里是 Devchen 的个人博客，创建于 2014 年。使用基于 Jekyllekyll @ GitHub 的 Yonsm 模板。"
